### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by WilfHass** [UBC-MDS/shiny_hotel_booking#23]
- [x] Add 1 new potential audience 

Interested users:
- [x] Include motivation behind app, explain what problem we are solving and why it is important
- [x] high level usage of the app

Contributions:
- [x] how to install and run app locally (installation instructions)
- [x] what we need help with and how to work in the project/how they can contribute

Other:
- [ ] GIF
- [x] Table of Contents

**Comment by roanraina** [comment]
- couldn't think of other users beyond hotel managers and travellers/hotel users
- adding an updated image of the app, gif may be added in future milestone
