### ISSUE TITLE
Section 2: Chart Box 

### ISSUE THREAD

**Issue by WilfHass** [UBC-MDS/shiny_hotel_booking#25]
Proposed charts:
- [x] Histogram of prices in the given country and date range @WilfHass 
- [x] Given a country, a time plot of the average booking price over the date range (line plot) @roanraina 
- [x] Histogram/bar chart of the busiest days over the date range @Mengjun74 
- [x] Heatmap @mrnabiz

**Comment by Mengjun74** [comment]
plot for the busiest days #33

**Comment by mrnabiz** [comment]
Closed and confirmed
