### ISSUE TITLE
Milestone1 feedback

### ISSUE THREAD

**Issue by ArmaghanSarvar** [UBC-MDS/shiny_hotel_booking#27]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

Section 1: Motivation and purpose: writing: 2/2, reasoning: 6/8
- More details can be provided on what the application visualizations will show instead of a high-level explanation. How exactly do the solutions help the specified audience? What is the presented information going to be?

Section 2: Description of data: writing: 2/2, reasoning: 7/8
- The variables have been explained; however, evident exploratory data analysis is not added (for example how many null/missing values does each variable have?)

Section 3: Research questions and usage scenarios: writing: 2/2, reasoning: 12/12
- The description informs what is needed to visualize from the data.
- The persona description specifies the benefits that the app could for this person.

Section 4: Description of the app and sketch: viz: 6/10, writing: 2/2, reasoning: 3/3
- It is better to specify what the visualizations are in the sketch as well and not rely 100% on the project description to explain the sketch. A user needs to be able to look at the sketch and know what the reactivity elements are. The plots are too general with no explanation.

Section 5: Teamwork contract and collaborative documentation: reasoning: 4/4

Section 6: Code of conduct: 1/1

Section 7: Contribution guidelines: 1/1

If anything is unclear, please feel free to ask questions. Great work!

**Comment by roanraina** [comment]
Thank you for the feedback. These issues do not need to be addressed in the final milestone. Closing the issue.
