### ISSUE TITLE
reorder the sketch

### ISSUE THREAD

**Issue by mrnabiz** [UBC-MDS/shiny_hotel_booking#28]
move the dropdowns and the date settings to a horizontal bar and assign 8 columns to the map and 4 columns to the bar charts.

**Comment by WilfHass** [comment]
Sketch has been updated to a picture of the (old) UI. Will need to be updated (GIF?) after addition of Mengjun's plot. Could also follow the little example usage I added right before the sketch in the `README`

**Comment by mrnabiz** [comment]
it has been updated based on the new UI

**Comment by mrnabiz** [comment]
Ready to be closed.

**Comment by mrnabiz** [comment]
closed :)
