### ISSUE TITLE
Improve the App

### ISSUE THREAD

**Issue by WilfHass** [UBC-MDS/shiny_hotel_booking#38]
Each member needs to choose (at least) 1 of these:
- [ ] add reactive functions to avoid code duplication (L3),
- [ ] dynamic UI elements (L5),
- [x] a download button (L5), @roanraina 
- [ ] add or upgrade a previous map as a choropleth map (L6),
- [ ] add a dockerfile (L7),
- [ ] add a downloadable report (L8)
- [x] incorporate at least 2 notifications or user feedback elements that are not spinners or progress bars (L8) @WilfHass 
- [ ] Comments from Peer Review
- [ ] TA feedback from the previous milestone

Fixes from the peer review:
- [x] Increase the size of the title
- [ ] Limit the range of the date selector to the min and max of the data range.

Fixes from Milestone 2 TA review: (Issue #43)
- [ ] Country selection can be improved in a way that the user can remove the selected countries easier.

From Florencia's Comments:
- [x] Add the interactivity of the plots
- [x] Remove the busiest day mark

- Must be an addition NOT a fix!
- Paste the link to commit in the submission with a description of the change (put them down below):
Ex.
```
Modification: Add a button to download the .csv file of the data in the "Provinces" tab 
Source: Peer review milestone 3 (paste the link to the comment)
Team member: Florencia
Commit/s: https://github.com/UBC-MDS/dashboard/commit/2314bb8f6ccc856d61ebf547e13e0da3a56b690a
```

Add those descriptions as comments!

**Comment by roanraina** [comment]
@mrnabiz @Mengjun74  can you guys implement your improvements today? I need the function/ui finalized before I can make tests.

**Comment by roanraina** [comment]
Modification: Add button to download the complete raw data as a .csv file.
Source: milestone 4 improvement list
Team member: Roan
Commit/s: a2718b2006e9996792d6427ed8987cbaeffffb4d a6941287234032e0a9ecb945314607432cd29eae 
PR: #48

**Comment by WilfHass** [comment]
Modification: Added notifications
Source: milestone 4 improvement list
Team member: Wilfred
Commit/s: https://github.com/UBC-MDS/shiny_hotel_booking/pull/49/commits/e896de05e516da552da9cdd09c7f281185a8e10a
PR: https://github.com/UBC-MDS/shiny_hotel_booking/pull/49

**Comment by Mengjun74** [comment]
Modification: edited title size
Source: milestone 4 improvement list
Team member: Mengjun
Commit/s: 9b48aca90c4f9a1c2586a7f6e90fcd2c4a55412e
PR: #46

**Comment by mrnabiz** [comment]
Modification: Chart Interactivity
Source: Milestone 4 improvement list
Team member: Nabi
Commit/s: https://github.com/UBC-MDS/shiny_hotel_booking/commit/380c0a712305f4aedd52003941ed20c73a51abf9
PR: #50

**Comment by roanraina** [comment]
4 improvements were made, one by each team member. Closing issue.
