### ISSUE TITLE
Production Ready App

### ISSUE THREAD

**Issue by WilfHass** [UBC-MDS/shiny_hotel_booking#40]
- [ ] reactive options work and give no errors
- [ ] maps and plots have legends if there are colours/shapes representing variables
- [ ] plot label axis is easy to understand
     - plot title should be larger than the y-axis and x-axis text size
- [ ] widgets have labels or titles
- [ ] layout and design facilitates data exploration
- [ ] re-read peer review feedback about visualizations
- [ ] add progress bars / spinners
- [ ] Improve `README.md` if there is feedback for it. Include link to feedback and commit of change.
- [ ] add short description to repo description
- [ ] add link to final deployed dashboard
- [ ] keywords describing plots/widgets/interactions [like this](https://github.com/UBC-MDS/dashr-heroku-deployment-demo)

**Comment by Mengjun74** [comment]
- [x] reactive options work and give no errors
- [x] maps and plots have legends if there are colours/shapes representing variables
- [x] plot label axis is easy to understand
     - plot title should be larger than the y-axis and x-axis text size
- [x] widgets have labels or titles
- [x] layout and design facilitates data exploration
- [x] re-read peer review feedback about visualizations
- [x] add progress bars / spinners
- [x] Improve `README.md` if there is feedback for it.  - No feedback for it.
- [x] add short description to repo description
- [x] add link to final deployed dashboard
- [x] keywords describing plots/widgets/interactions [like this](https://github.com/UBC-MDS/dashr-heroku-deployment-demo)
