### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/shiny_hotel_booking#43]
> **Congratulations on finishing milestone 1!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## 1. Submission instructions
rubric={mechanics:4}

Well done!

## 2. Developing your Shiny App
rubric={mechanics:15, quality:5, viz:15, accuracy:7}

Well done!

 Comments:
-Country selection can be improved in a way that the user can remove the selected countries easier.

## 3. Reflection
rubric={reasoning:6}

Well done!

## 4.Improve the README
rubric={reasoning:6}

Well done!

**Comment by roanraina** [comment]
Thanks for the feedback! The country selection feedback has been incorporated into Issue #38. Closing this issue.
